version: "3.8"

services:
  db:
    image: postgres:latest
    restart: always
    container_name: gameshelf-database
    environment:
      POSTGRES_USER: ${GAMESHELF_POSTGRES_USER}
      POSTGRES_PASSWORD: ${GAMESHELF_POSTGRES_PASSWORD}
      POSTGRES_DB: gameshelf
    volumes:
      - "${DATABASE_VOLUME_PATH}:/var/lib/postgresql/data"
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${GAMESHELF_PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${GAMESHELF_PGADMIN_PASSWORD}
    ports:
      - "8082:80"
    depends_on:
      - db

  backend:
    build:
      context: ./back
      dockerfile: Dockerfile
    container_name: gameshelf-backend
    ports:
      - "8081:8081"
    env_file:
      - ./back/.env
    depends_on:
      - db
